apiVersion: apps/v1
kind: Deployment
metadata:
  name: whois-server
  labels:
    app: whois
    part: port43
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whois
      part: port43
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
      labels:
        app: whois
        part: port43
    spec:
      tolerations:
        - key: special
          operator: Equal
          value: edge
          effect: NoSchedule
      containers:
        - name: whois
          image: as207960/whois-server:5
          imagePullPolicy: Always
          ports:
            - containerPort: 43
          env:
            - name: GRPC_SERVER
              value: "http://domains-whois-grpc:50051"
---
apiVersion: v1
kind: Service
metadata:
  name: whois-server
  labels:
    app: whois
    part: port43
spec:
  selector:
    app: whois
    part: port43
  ports:
    - port: 43
      targetPort: 43
      protocol: TCP
  type: LoadBalancer
